name: carichess
description: La révolution des échecs.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.4.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/pieces/
    - assets/images/pieces/old/

  fonts:
    - family: November
      fonts:
        - asset: assets/fonts/November-Regular.ttf
